// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vdual_sinegen.cpp"
#include "Vdual_sinegen___024root__DepSet_h791e10f0__0.cpp"
#include "Vdual_sinegen___024root__DepSet_h276aa84c__0.cpp"
#include "Vdual_sinegen__Trace__0.cpp"
#include "Vdual_sinegen___024root__Slow.cpp"
#include "Vdual_sinegen___024root__DepSet_h791e10f0__0__Slow.cpp"
#include "Vdual_sinegen___024root__DepSet_h276aa84c__0__Slow.cpp"
#include "Vdual_sinegen__Syms.cpp"
#include "Vdual_sinegen__Trace__0__Slow.cpp"
#include "Vdual_sinegen__TraceDecls__0__Slow.cpp"
